title: Pirátská strana Praha
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://praha.pirati.cz" # the base hostname & protocol for your site

# mediaStorage: praha

administrator:
  email: jitka.novotna@pirati.cz, jan.louzek@pirati.cz, jan.suchanek@gmail.com, marek.krejpsky@pirati.cz # maily kam jdou vystupy oddělené čárkou


organization:
  name: Pirátská strana Praha
  shortName: Piráti Praha
  email: kodo-praha@pirati.cz
  phone: +420 703 681 682
  address: |
    Na Moráni 3,
    120 00 Praha 2
  mapLink: https://mapy.cz/zakladni?x=14.4151543&y=50.0733415&z=18&source=addr&id=9018965&q=Na%20Mor%C3%A1ni%203
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

calendar:
  apiKey: AIzaSyBdjZxz4r9lPyD3CiSxQa6G3mf47ezI7Ks
  id: rm0h4oqjk2j2o0615sc4d1slfk@group.calendar.google.com
  title: "Celopražský kalendář"
  page: pripoj-se/kalendar

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/CeskaPiratskaStranaPraha/"
  appId: 1526197851008996
markdown: kramdown

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

flicker:
  profilePage: https://www.flickr.com/photos/188991349@N06/

forum:
  page: https://forum.pirati.cz/viewforum.php?f=78&sid=44b065968620303e7f4058202f146b94  i

github:
  url: https://github.com/pirati-web/praha.pirati.cz/
  branch: master


youtube:
  url: "https://www.youtube.com/channel/UC6zpUdw-MTT1WUBDo4K-nHA/videos" 


##  TECHNICKÁ ČÁST  
    
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-environment-variables
paginate_path: "/aktuality/:num/"
paginate: 11

twitter_username: jekyllrb
github_username:  jekyll

theme: jekyll-theme-pirati
exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - foto
        - work
        - personContact
        - people
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      rbar:
        - foto
        - personContact
        - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
      #         - garant
         - program

fb: https://www.facebook.com/CeskaPiratskaStranaPraha/
tw: piratipraha

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.4.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - assets/img/posts
    - assets/snippet
    - _sass
